[package]
name = "mandelbrot_explorer"
version = "0.1.0"
authors = ["ujjujjuj <ujjwaldimri@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "*"
